Move examples to separate files
yiisoft/actions pull request #29
Opened 2022-12-20 18:21 UTC by bdFregat

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌
| Fixed issues  |  Move examples to separate files #14

2022-12-22 07:21 UTC, vjik requested changes

2022-12-22 07:21 UTC, vjik commented on docs/composer.md
> +### Using [Composer require checker](https://github.com/maglnet/ComposerRequireChecker)
```suggestion
# Using [Composer require checker](https://github.com/maglnet/ComposerRequireChecker)
```

And rename to `composer-require-checker.md`

2022-12-22 07:21 UTC, vjik commented on docs/php-bench.md
> +### Example of use of the action [PHPBench](https://github.com/phpbench/phpbench)
```suggestion
# Using [PHPBench](https://github.com/phpbench/phpbench)
```

And rename to `phpbench.md`

2022-12-22 07:21 UTC, vjik commented on docs/php-unit.md
> +### Example of use of the action [PHPUnit](https://github.com/sebastianbergmann/phpunit)
```suggestion
# Using [PHPUnit](https://github.com/sebastianbergmann/phpunit)
```

And rename to `phpunit.md`

2022-12-22 07:21 UTC, vjik commented on docs/psalm.md
> +### Example of use of the action [PSALM](https://github.com/vimeo/psalm)
```suggestion
# Using [Psalm](https://github.com/vimeo/psalm)
```

2022-12-22 07:21 UTC, vjik commented on docs/rector.md
> +### Example of use of the action [RECTOR](https://github.com/rectorphp/rector)
```suggestion
### Using [Rector](https://github.com/rectorphp/rector)
```

2022-12-22 07:21 UTC, vjik commented on docs/roave-infection.md
> +### Example of use of the action [ROAVE-INFECTION](https://github.com/roave/infection-static-analysis-plugin)
```suggestion
# Using [Infection](https://infection.github.io/) mutation framework with [Infection Static Analysis Plugin](https://github.com/Roave/infection-static-analysis-plugin)
```

2022-12-22 07:21 UTC, vjik commented on README.md
> +## Examples:
```suggestion
```

2022-12-22 07:21 UTC, vjik commented on README.md
> +- [PSALM](docs/psalm.md)
```suggestion
- [Psalm](docs/psalm.md)
```

2022-12-22 07:21 UTC, vjik commented on README.md
> +- [Roave Infection](docs/roave-infection.md)
```suggestion
- [Infection with Static Analysis Plugin](docs/roave-infection.md)
```

2022-12-23 09:08 UTC, samdark approved these changes

2022-12-23 09:08 UTC, merged

2022-12-23 09:08 UTC, samdark commented
Thanks!