Add rector usage `README.md`
yiisoft/actions pull request #8
Opened 2022-09-27 16:46 UTC by terabytesoftw

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌

2022-09-27 19:11 UTC, xepozz requested changes

2022-09-27 19:11 UTC, xepozz commented on README.md
> +
```suggestion
```

2022-09-27 19:51 UTC, xepozz approved these changes

2022-09-28 07:01 UTC, arogachev approved these changes

2022-09-28 08:27 UTC, roxblnfk commented
What do you think there should be an example of `rector.php` here?

2022-09-29 11:01 UTC, merged